//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG7312ST10202241.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROG7312ST10202241.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Image Or Document.
        /// </summary>
        internal static string AttachImageOrDocument {
            get {
                return ResourceManager.GetString("AttachImageOrDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Media.
        /// </summary>
        internal static string AttachMediaBtn {
            get {
                return ResourceManager.GetString("AttachMediaBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Main Menu.
        /// </summary>
        internal static string BackToMainMenuBtn {
            get {
                return ResourceManager.GetString("BackToMainMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryLbl {
            get {
                return ResourceManager.GetString("CategoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads.
        /// </summary>
        internal static string CategoryRoads {
            get {
                return ResourceManager.GetString("CategoryRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitation.
        /// </summary>
        internal static string CategorySanitation {
            get {
                return ResourceManager.GetString("CategorySanitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string CategoryUtilities {
            get {
                return ResourceManager.GetString("CategoryUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string closeBtn {
            get {
                return ResourceManager.GetString("closeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string descriptionLbl {
            get {
                return ResourceManager.GetString("descriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string Form1Title {
            get {
                return ResourceManager.GetString("Form1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Reported Successfully!.
        /// </summary>
        internal static string IssueReportedSuccessfully {
            get {
                return ResourceManager.GetString("IssueReportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Events And Announcements.
        /// </summary>
        internal static string LocalEventsAndAnnouncements {
            get {
                return ResourceManager.GetString("LocalEventsAndAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Events And Announcements.
        /// </summary>
        internal static string LocalEventsAndAnnouncementsTitle {
            get {
                return ResourceManager.GetString("LocalEventsAndAnnouncementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        internal static string locationLbl {
            get {
                return ResourceManager.GetString("locationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string Nofileselected {
            get {
                return ResourceManager.GetString("Nofileselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Category.
        /// </summary>
        internal static string PleaseEnterACategory {
            get {
                return ResourceManager.GetString("PleaseEnterACategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Description .
        /// </summary>
        internal static string PleaseEnterADescription {
            get {
                return ResourceManager.GetString("PleaseEnterADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Location.
        /// </summary>
        internal static string PleaseEnterALocation {
            get {
                return ResourceManager.GetString("PleaseEnterALocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issues.
        /// </summary>
        internal static string ReportIssuesBtn {
            get {
                return ResourceManager.GetString("ReportIssuesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issues .
        /// </summary>
        internal static string ReportIssuesTitle {
            get {
                return ResourceManager.GetString("ReportIssuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Status.
        /// </summary>
        internal static string ServiceRequestStatusBtn {
            get {
                return ResourceManager.GetString("ServiceRequestStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitBtn {
            get {
                return ResourceManager.GetString("SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reports.
        /// </summary>
        internal static string ViewReportsFormBtn {
            get {
                return ResourceManager.GetString("ViewReportsFormBtn", resourceCulture);
            }
        }
    }
}
